let D=load(),state={type:null,level:null,mode:null,qs:[],i:0,hits:0,correct:null,locked:false,grid:null,path:[],target:[],daily:false,total:GAME.total};
const A=document.getElementById('app');
const mix=a=>[...a].sort(()=>Math.random()-.5);
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const stats=id=>D.estadisticas[id]||{partidas:0,aciertos:0,respuestas:0};
const today=()=>new Date().toLocaleDateString('sv-SE');
function ensureDaily(){if(D.retosDiarios.fecha!==today())D.retosDiarios={fecha:today(),sumas:false,restas:false,sopa:false,premio:false};save(D);}
function xpNeeded(level){return 260+(level-1)*85;}
function xpPanel(){const need=xpNeeded(D.nivelJugador),pct=Math.min(100,Math.round(D.xp/need*100));return `<div class="xp-card"><div class="xp-head"><b>Nivel ${D.nivelJugador}</b><span>${D.xp} / ${need} XP</span></div><div class="xp-track"><div class="xp-fill" style="width:${pct}%"></div></div><div class="next-gift">Siguiente nivel: +25 💎</div></div>`;}
const ACHIEVEMENTS=[
  {id:'first_game',icon:'🎮',name:'Primera partida',desc:'Termina una actividad',test:()=>totalGames()>=1,reward:5},
  {id:'ten_correct',icon:'⭐',name:'Buen comienzo',desc:'Consigue 10 respuestas correctas',test:()=>D.totalAciertos>=10,reward:8},
  {id:'fifty_correct',icon:'🏅',name:'Aprendiz constante',desc:'Consigue 50 respuestas correctas',test:()=>D.totalAciertos>=50,reward:15},
  {id:'daily_complete',icon:'☀️',name:'Día completo',desc:'Completa los tres retos diarios',test:()=>D.retosDiarios.premio,reward:10},
  {id:'level_3',icon:'🚀',name:'Nivel 3',desc:'Alcanza el nivel 3',test:()=>D.nivelJugador>=3,reward:12}
];
let pendingAchievements=[],pendingLevelRewards=[];
function totalGames(){return Object.values(D.estadisticas||{}).reduce((n,s)=>n+(s.partidas||0),0);}
function checkAchievements(){for(const a of ACHIEVEMENTS){if(!D.logros.includes(a.id)&&a.test()){D.logros.push(a.id);D.diamantes+=a.reward;pendingAchievements.push(a);}}save(D);}
function showPendingAchievement(){if(!pendingAchievements.length)return false;const a=pendingAchievements.shift();layout(`<div class="levelup"><div class="levelup-stars">✨ 🏆 ✨</div><h2>¡Nuevo logro!</h2><div class="achievement-big">${a.icon}</div><h3>${a.name}</h3><p>${a.desc}</p><div class="daily-prize">+${a.reward} 💎</div><button class="btn primary" onclick="home()">Continuar</button></div>`);return true;}
function achievements(){checkAchievements();layout(`<div class="top"><button class="btn secondary back" onclick="home()">← Volver</button>${diamond()}</div><h2>Logros</h2><div class="achievement-list">${ACHIEVEMENTS.map(a=>{const ok=D.logros.includes(a.id);return `<div class="achievement-card ${ok?'unlocked':'locked'}"><div class="achievement-icon">${ok?a.icon:'🔒'}</div><div><b>${a.name}</b><div class="muted">${a.desc}</div><div class="achievement-reward">${ok?'Conseguido':'Premio: '+a.reward+' 💎'}</div></div></div>`;}).join('')}</div>`);}
function progressSummary(){const games=totalGames();return `<div class="progress-summary"><div><b>${D.totalAciertos}</b><span>Aciertos</span></div><div><b>${games}</b><span>Partidas</span></div><div><b>${D.logros.length}/${ACHIEVEMENTS.length}</b><span>Logros</span></div></div>`;}
function giveXP(amount){D.xp+=amount;while(D.xp>=xpNeeded(D.nivelJugador)){D.xp-=xpNeeded(D.nivelJugador);D.nivelJugador++;D.diamantes+=25;pendingLevelRewards.push('25 diamantes');}save(D);}
function showPendingLevel(){if(!pendingLevelRewards.length)return false;const rewards=[...pendingLevelRewards];pendingLevelRewards=[];layout(`<div class="levelup"><div class="levelup-stars">✨ 🎉 ✨</div><h2>¡Has subido al nivel ${D.nivelJugador}!</h2><div class="gift-box">🎁</div><p>Has conseguido:</p><h3>${rewards.join('<br>')}</h3><button class="btn primary" onclick="home()">Continuar</button></div>`);return true;}
function dailyHTML(){ensureDaily();const r=D.retosDiarios,done=[r.sumas,r.restas,r.sopa].filter(Boolean).length;const row=(type,ok,label,time)=>`<button class="daily-row ${ok?'done locked':''}" ${ok?'disabled aria-disabled="true"':`onclick="startDaily('${type}')"`}><span>${ok?'🔒 ✅':'⬜'} ${label}</span><small>${ok?'Completado':time}</small></button>`;return `<div class="daily-card"><div class="daily-title"><b>🎯 Retos de hoy</b><span>${done}/3</span></div>${row('suma',r.sumas,'5 sumas','2 min')}${row('resta',r.restas,'5 restas','2 min')}${row('sopa',r.sopa,'1 sopa de letras','2 min')}<div class="daily-prize">${r.premio?'🎁 Premio diario conseguido · vuelve mañana':'🎁 Completa los 3: +10 💎 y +10 XP'}</div></div>`;}
function dailyDifficulty(){const step=Math.min(5,Math.floor((D.retosCompletadosTotal||0)/9));return{mathMax:10+step*2,soupLevel:step<2?GAME.levels.sopa[0]:step<4?GAME.levels.sopa[1]:GAME.levels.sopa[2]};}
function startDaily(type){ensureDaily();const r=D.retosDiarios;if((type==='suma'&&r.sumas)||(type==='resta'&&r.restas)||(type==='sopa'&&r.sopa))return;const dif=dailyDifficulty();if(type==='suma')startMath('suma',{...GAME.levels.suma[0],max:dif.mathMax,desc:`Resultado hasta ${dif.mathMax}`},true);else if(type==='resta')startMath('resta',{...GAME.levels.resta[0],max:dif.mathMax,desc:`Hasta ${dif.mathMax}, sin negativos`},true);else startSoup(dif.soupLevel,true);}
function markDaily(type){ensureDaily();let added=false;if(type==='suma'&&!D.retosDiarios.sumas){D.retosDiarios.sumas=true;added=true;}if(type==='resta'&&!D.retosDiarios.restas){D.retosDiarios.restas=true;added=true;}if(type==='sopa'&&!D.retosDiarios.sopa){D.retosDiarios.sopa=true;added=true;}if(added)D.retosCompletadosTotal=(D.retosCompletadosTotal||0)+1;if(D.retosDiarios.sumas&&D.retosDiarios.restas&&D.retosDiarios.sopa&&!D.retosDiarios.premio){D.retosDiarios.premio=true;D.diamantes+=10;giveXP(10);}save(D);}
function diamond(flash=false){return `<div id="diamond" class="diamond ${flash?'flash':''}">💎 <span>${D.diamantes}</span></div>`;}
function layout(content){A.innerHTML=`<div class="wrap"><div class="card">${content}</div></div>`;}
let audioCtx=null;
function playChime(kind='ok'){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const now=audioCtx.currentTime,osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type='sine';osc.frequency.setValueAtTime(kind==='ok'?660:220,now);osc.frequency.exponentialRampToValueAtTime(kind==='ok'?880:180,now+.11);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.055,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+.14);osc.connect(gain).connect(audioCtx.destination);osc.start(now);osc.stop(now+.15);}catch(e){}}
function home(){ensureDaily();checkAchievements();if(showPendingLevel())return;if(showPendingAchievement())return;layout(`
<div class="home-head"><div class="brand"><div class="brand-mark">AJ</div><div><h1>Aprendo jugando</h1><div class="muted">V2.6.0 · progresión de matemáticas</div></div></div>${diamond()}</div>
${xpPanel()}
<div class="dashboard-grid"><div class="dashboard-main">${dailyHTML()}</div><div class="dashboard-side">${progressSummary()}<button class="btn secondary side-action" onclick="achievements()">🏆 Ver logros</button></div></div>
<h3 class="section-title">Juegos</h3>
<div class="game-grid">
<button class="game-card game-sum" onclick="levels('suma')"><span class="game-icon">＋</span><b>Sumas</b><small>10 niveles · 10 ejercicios</small></button>
<button class="game-card game-sub" onclick="levels('resta')"><span class="game-icon">−</span><b>Restas</b><small>10 niveles · 10 ejercicios</small></button>
<button class="game-card game-letters" onclick="letters()"><span class="game-icon">Aa</span><b>Letras</b><small>Completa palabras</small></button>
<button class="game-card game-soup" onclick="levels('sopa')"><span class="game-icon">▦</span><b>Sopa de letras</b><small>Encuentra palabras</small></button>
</div>
<div class="bottom-actions"><button class="btn secondary" onclick="parents()">⚙️ Zona de padres</button></div>`);}
function mathLevelDone(n){return stats(n.id).partidas>0;}
function mathLevelUnlocked(t,index){return index===0||mathLevelDone(GAME.levels[t][index-1]);}
function mathDiamonds(n,repeat=false){return repeat?n.level:n.level+4;}
function levels(t){
  state.type=t;
  const title=t==='suma'?'Niveles de sumas':t==='resta'?'Niveles de restas':'Sopa de letras';
  if(t==='suma'||t==='resta'){
    const rows=GAME.levels[t].map((n,index)=>{
      const s=stats(n.id),done=s.partidas>0,unlocked=mathLevelUnlocked(t,index),p=s.respuestas?Math.round(s.aciertos/s.respuestas*100):0,reward=mathDiamonds(n,done);
      return `<div class="row level-row ${done?'level-done':''} ${unlocked?'':'level-locked'}"><div class="level-main"><div class="level-title"><b>${done?'✅ ':unlocked?'':'🔒 '}${n.name}</b>${done?'<span class="done-badge">HECHO</span>':''}</div><div class="muted">${n.desc}</div><div class="level-meta"><span>10 ejercicios</span><span>💎 ${reward} ${done?'al repetir':'primera vez'}</span>${done?`<span>Aciertos: ${p}%</span>`:''}</div></div><div class="actions">${unlocked?`<button class="small play" onclick='startMath(${JSON.stringify(t)},${JSON.stringify(n)})'>${done?'Repetir':'Jugar'}</button>`:'<button class="small locked-button" disabled>Bloqueado</button>'}</div></div>`;
    }).join('');
    layout(`<div class="top"><button class="btn secondary back" onclick="home()">← Volver</button>${diamond()}</div><h2>${title}</h2><p class="muted level-help">Completa un nivel una vez para desbloquear el siguiente. Puedes repetir cualquier nivel desbloqueado.</p><div class="levels">${rows}</div>`);
    return;
  }
  layout(`<div class="top"><button class="btn secondary back" onclick="home()">← Volver</button>${diamond()}</div><h2>${title}</h2><div class="levels">${GAME.levels[t].map(n=>{const s=stats(n.id),p=s.respuestas?Math.round(s.aciertos/s.respuestas*100):0;return `<div class="row"><div><b>${n.name}</b><div class="muted">${n.desc}</div><div class="muted">Jugado: ${s.partidas} · Aciertos: ${p}%</div></div><div class="actions"><button class="small play" onclick='startSoup(${JSON.stringify(n)})'>Jugar</button><button class="small reset" onclick="resetLevel('${n.id}')">Reset</button></div></div>`;}).join('')}</div>`);
}
function resetLevel(id){if(confirm('¿Borrar estadísticas?')){delete D.estadisticas[id];save(D);levels(state.type);}}
function letters(){layout(`<div class="top"><button class="btn secondary back" onclick="home()">← Volver</button>${diamond()}</div><h2>Letras</h2><p class="muted">Mira la imagen y completa varias letras.</p><div class="grid"><button class="btn primary" onclick="startLetters('inicial')">Completar desde el inicio</button><button class="btn primary" onclick="startLetters('completar')">Completar letras ocultas</button></div>`);}
function startMath(t,n,daily=false){
  const total=daily?GAME.dailyMathTotal:GAME.mathTotal;
  state={...state,type:t,level:n,mode:null,qs:[],i:0,hits:0,daily,total};
  if(daily){
    const max=n.max||10;
    for(let a=1;a<=max;a++)for(let b=1;b<=max;b++){
      if(t==='suma'&&a+b<=max)state.qs.push({a,b,r:a+b});
      if(t==='resta'&&b<a)state.qs.push({a,b,r:a-b});
    }
  }else{
    for(let a=1;a<=n.aMax;a++)for(let b=1;b<=n.bMax;b++){
      if(t==='suma'&&(!n.resultMax||a+b<=n.resultMax))state.qs.push({a,b,r:a+b});
      if(t==='resta'&&b<a)state.qs.push({a,b,r:a-b});
    }
  }
  state.qs=mix(state.qs).slice(0,total);
  question();
}
function startLetters(m){state={...state,type:'letras',mode:m,level:null,qs:mix(GAME.words.filter(w=>w.word.length>=4)).slice(0,GAME.total),i:0,hits:0,daily:false,total:GAME.total,missing:[],missingStep:0,currentWord:null};question();}
function question(){state.locked=false;if(state.i>=state.total)return finish();const q=state.qs[state.i],isL=state.type==='letras';if(isL){state.currentWord=q;const count=Math.min(q.word.length-1,state.mode==='inicial'?2:Math.max(2,Math.min(3,Math.floor(D.nivelJugador/4)+2)));let positions=[];if(state.mode==='inicial')positions=[0,1].filter(x=>x<q.word.length);else positions=mix([...Array(q.word.length).keys()]).slice(0,count).sort((a,b)=>a-b);state.missing=positions;state.missingStep=0;renderLetterStep();state.i++;return;}state.correct=q.r;const prompt=`${q.a} ${state.type==='suma'?'+':'−'} ${q.b}`;let optsSet=new Set([q.r]);while(optsSet.size<3){const v=q.r+rnd(-5,5);if(v>=0)optsSet.add(v);}const opts=mix([...optsSet]);layout(`<div class="top"><button class="btn secondary back" onclick="levels('${state.type}')">← Salir</button>${diamond()}</div><div class="muted">Ejercicio ${state.i+1} de ${state.total}</div><div class="question">${prompt}</div><div class="answers">${opts.map(o=>`<button class="answer" onclick="answer('${o}',this)">${o}</button>`).join('')}</div><div id="msg" class="muted msg"></div>`);state.i++;}
function renderLetterStep(){const q=state.currentWord,pos=state.missing[state.missingStep];state.correct=q.word[pos];const shown=[...q.word].map((ch,i)=>state.missing.includes(i)?(state.missing.indexOf(i)<state.missingStep?ch:'_'):ch).join('');const letters='ABCDEFGHIJKLMNÑOPQRSTUVWXYZ';let s=new Set([state.correct]);while(s.size<3)s.add(letters[rnd(0,letters.length-1)]);const opts=mix([...s]);layout(`<div class="top"><button class="btn secondary back" onclick="letters()">← Salir</button>${diamond()}</div><div class="muted">Palabra ${state.i+1} de ${state.total} · letra ${state.missingStep+1} de ${state.missing.length}</div><div class="image-box only-image">${q.icon}</div><div class="question letter-word">${shown}</div><div class="answers">${opts.map(o=>`<button class="answer" onclick="answerLetter('${o}',this)">${o}</button>`).join('')}</div><div id="msg" class="muted msg"></div>`);}
function answerLetter(v,b){if(state.locked)return;if(String(v)===String(state.correct)){b.classList.add('correct');playChime('ok');state.missingStep++;document.getElementById('msg').textContent='¡Bien!';if(state.missingStep>=state.missing.length){state.locked=true;state.hits++;rewardOne();setTimeout(question,750);}else setTimeout(()=>{state.locked=false;renderLetterStep();},450);}else{b.classList.add('wrong');playChime('bad');document.getElementById('msg').textContent='Prueba otra vez';setTimeout(()=>b.classList.remove('wrong'),450);}}
function answer(v,b){if(state.locked)return;state.locked=true;if(String(v)===String(state.correct)){state.hits++;if((state.type==='suma'||state.type==='resta')&&!state.daily){rewardMathCorrect();document.getElementById('msg').textContent='¡Muy bien!';}else{rewardOne();document.getElementById('msg').textContent='¡Muy bien! +1 💎';}b.classList.add('correct');}else{playChime('bad');b.classList.add('wrong');document.getElementById('msg').textContent='Era '+state.correct;document.querySelectorAll('.answer').forEach(x=>{if(String(x.textContent)===String(state.correct))x.classList.add('correct');});}setTimeout(question,900);}
function rewardMathCorrect(){D.totalAciertos++;giveXP(2);save(D);playChime('ok');}
function rewardOne(){D.diamantes++;D.totalAciertos++;giveXP(2);save(D);playChime('ok');animateDiamond();}
function animateDiamond(){const el=document.getElementById('diamond');if(el){const span=el.querySelector('span');if(span)span.textContent=D.diamantes;el.classList.remove('flash');void el.offsetWidth;el.classList.add('flash');}const t=document.createElement('div');t.className='toast';t.textContent='+1 💎';document.body.appendChild(t);setTimeout(()=>t.remove(),900);}
function finish(){
  if((state.type==='suma'||state.type==='resta')&&!state.daily){
    const s=stats(state.level.id),wasDone=s.partidas>0;
    s.partidas++;s.aciertos+=state.hits;s.respuestas+=state.total;D.estadisticas[state.level.id]=s;
    const reward=mathDiamonds(state.level,wasDone),perfect=state.hits===state.total,xp=5+(perfect?5:0);
    D.diamantes+=reward;giveXP(xp);checkAchievements();save(D);
    layout(`<div class="top"><h2>¡Nivel completado!</h2>${diamond(true)}</div><div class="question score">${state.hits} de ${state.total}</div><p class="center reward-line">+${reward} 💎 · +${xp} XP</p><p class="center muted">${wasDone?'Premio de repetición':'¡Nivel marcado como hecho! El siguiente nivel ya está desbloqueado.'}</p><div class="grid"><button class="btn primary" onclick="startMath('${state.type}',${JSON.stringify(state.level)})">Jugar otra vez</button><button class="btn secondary" onclick="levels('${state.type}')">Volver a niveles</button></div>`);
    return;
  }
  if(state.type!=='letras'){const s=stats(state.level.id);s.partidas++;s.aciertos+=state.hits;s.respuestas+=state.total;D.estadisticas[state.level.id]=s;}
  const perfect=state.hits===state.total,bonus=perfect?5:3,xp=5+(perfect?5:0);D.diamantes+=bonus;giveXP(xp);if(state.daily)markDaily(state.type);checkAchievements();save(D);layout(`<div class="top"><h2>¡Actividad terminada!</h2>${diamond(true)}</div><div class="question score">${state.hits} de ${state.total}</div><p class="center reward-line">+${bonus} 💎 · +${xp} XP</p><div class="grid"><button class="btn primary" onclick="${state.daily?'home()':state.type==='letras'?`startLetters('${state.mode}')`:`startMath('${state.type}',${JSON.stringify(state.level)})`}">${state.daily?'Volver a los retos':'Jugar otra vez'}</button><button class="btn secondary" onclick="${state.type==='letras'?'letters()':`levels('${state.type}')`}">Volver al menú</button></div>`);}
function startSoup(n,daily=false){state={...state,type:'sopa',level:n,mode:null,qs:mix(GAME.words.filter(w=>w.word.length<=n.size)).slice(0,daily?1:3),i:0,hits:0,daily};soupQuestion();}
function soupQuestion(){if(state.i>=state.qs.length)return finishSoup();state.locked=false;state.path=[];const q=state.qs[state.i],built=buildGrid(q.word,state.level.size,state.level.dirs);state.grid=built.grid;state.target=built.target;const cols=`repeat(${state.level.size},1fr)`;layout(`<div class="top"><button class="btn secondary back" onclick="levels('sopa')">← Salir</button>${diamond()}</div><div class="muted">Palabra ${state.i+1} de ${state.qs.length}</div><div class="word-target"><div class="word-picture">${q.icon}</div><div><div class="word-name">${q.word}</div><div class="word-hint">Toca la primera y la última letra.</div></div></div><div id="wordGrid" class="word-grid" style="grid-template-columns:${cols}">${built.grid.flatMap((row,r)=>row.map((letter,c)=>`<button class="word-cell" data-r="${r}" data-c="${c}" onclick="pickSoup(${r},${c})">${letter}</button>`)).join('')}</div><div id="wordStatus" class="word-status"></div>`);}
function buildGrid(word,size,dirs){const grid=Array.from({length:size},()=>Array(size).fill(''));const dir=dirs[rnd(0,dirs.length-1)];let dr=0,dc=1;if(dir==='v'){dr=1;dc=0;}if(dir==='hr'){dr=0;dc=-1;}if(dir==='vr'){dr=-1;dc=0;}const maxR=dr===1?size-word.length:dr===-1?word.length-1:size-1,minR=dr===-1?word.length-1:0,maxC=dc===1?size-word.length:dc===-1?word.length-1:size-1,minC=dc===-1?word.length-1:0,sr=rnd(minR,maxR),sc=rnd(minC,maxC),target=[];[...word].forEach((ch,i)=>{const r=sr+dr*i,c=sc+dc*i;grid[r][c]=ch;target.push([r,c]);});const abc='ABCDEFGHIJKLMNÑOPQRSTUVWXYZ';for(let r=0;r<size;r++)for(let c=0;c<size;c++)if(!grid[r][c])grid[r][c]=abc[rnd(0,abc.length-1)];return{grid,target};}
function pickSoup(r,c){if(state.locked)return;const p=state.path;if(!p.length){state.path=[[r,c]];paintPath();document.getElementById('wordStatus').textContent='Ahora toca la última letra.';return;}const start=p[0],line=getLine(start,[r,c]);state.path=line;paintPath();const ok=samePath(line,state.target)||samePath([...line].reverse(),state.target);if(ok){state.locked=true;state.hits++;rewardOne();document.getElementById('wordStatus').textContent='¡Encontrada! +1 💎';line.forEach(([rr,cc])=>cellAt(rr,cc).classList.add('found'));state.i++;setTimeout(soupQuestion,1050);}else{document.getElementById('wordStatus').textContent='Prueba otra vez.';setTimeout(()=>{state.path=[];paintPath();document.getElementById('wordStatus').textContent='';},550);}}
function getLine(a,b){const dr=Math.sign(b[0]-a[0]),dc=Math.sign(b[1]-a[1]);if(!(a[0]===b[0]||a[1]===b[1]))return[a,b];const len=Math.max(Math.abs(b[0]-a[0]),Math.abs(b[1]-a[1]))+1;return Array.from({length:len},(_,i)=>[a[0]+dr*i,a[1]+dc*i]);}
function samePath(a,b){return a.length===b.length&&a.every((p,i)=>p[0]===b[i][0]&&p[1]===b[i][1]);}
function cellAt(r,c){return document.querySelector(`.word-cell[data-r="${r}"][data-c="${c}"]`);}
function paintPath(){document.querySelectorAll('.word-cell').forEach(x=>x.classList.remove('selected'));state.path.forEach(([r,c])=>{const x=cellAt(r,c);if(x)x.classList.add('selected');});}
function finishSoup(){const s=stats(state.level.id);s.partidas++;s.aciertos+=state.hits;s.respuestas+=state.qs.length;D.estadisticas[state.level.id]=s;const perfect=state.hits===state.qs.length,bonus=perfect?5:3,xp=5+(perfect?5:0);D.diamantes+=bonus;giveXP(xp);if(state.daily)markDaily('sopa');checkAchievements();save(D);layout(`<div class="top"><h2>¡Sopa completada!</h2>${diamond(true)}</div><div class="question score">${state.hits} de ${state.qs.length}</div><p class="center reward-line">+${bonus} 💎 · +${xp} XP</p><div class="grid"><button class="btn primary" onclick="${state.daily?'home()':`startSoup(${JSON.stringify(state.level)})`}">${state.daily?'Volver a los retos':'Jugar otra vez'}</button><button class="btn secondary" onclick="levels('sopa')">Volver a niveles</button></div>`);}
function parents(){layout(`<div class="top"><button class="btn secondary back" onclick="home()">← Volver</button>${diamond()}</div><h2>Zona de padres</h2><div class="parent-grid"><div class="parent-card"><h3>👤 Jugador</h3><label>Nombre</label><input id="nameInput" type="text" maxlength="24" value="${escapeHTML(D.perfil.nombre)}"><button class="btn secondary" onclick="setName()">Guardar nombre</button></div><div class="parent-card"><h3>💾 Progreso</h3><div class="grid"><button class="btn secondary" onclick="exportData()">Exportar progreso</button><label class="btn secondary file-label" for="importFile">Importar progreso</label><input id="importFile" type="file" accept=".json,application/json" onchange="importData(event)" hidden></div></div><div class="parent-card"><h3>⚠️ Reinicio</h3><button class="btn danger" onclick="resetAll()">Borrar todo el progreso</button></div></div>`);}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function setName(){const i=document.getElementById('nameInput');D.perfil.nombre=(i?.value||'Jugador').trim().slice(0,24)||'Jugador';save(D);alert('Nombre guardado');}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(D,null,2)],{type:'application/json'}));a.download='progreso-aprendo-jugando.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function importData(e){const file=e.target.files&&e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{localStorage.setItem(STORE,r.result);D=load();alert('Progreso importado');home();}catch{alert('Archivo no válido');}};r.readAsText(file);}
function resetAll(){if(confirm('¿Borrar todo el progreso? Esta acción no se puede deshacer.')){localStorage.removeItem(STORE);D=load();home();}}
home();
