/**
 * Sistema de niveles y catálogo del avatar paper-doll.
 * V3.15 · incorpora personaje Felino y categoría 1.
 */
const AVATAR_LEVELS=[
{id:'aprendiz',name:'Aprendiz',order:1},{id:'explorador',name:'Explorador',order:2},{id:'aventurero',name:'Aventurero',order:3},{id:'guerrero',name:'Guerrero',order:4},{id:'heroe',name:'Héroe',order:5},{id:'campeon',name:'Campeón',order:6},{id:'maestro',name:'Maestro',order:7},{id:'leyenda',name:'Leyenda',order:8}];
const LEVEL_BY_ID=Object.fromEntries(AVATAR_LEVELS.map(x=>[x.id,x]));
const LEVEL_BY_ORDER=Object.fromEntries(AVATAR_LEVELS.map(x=>[x.order,x]));
const EQUIPMENT_TIERS=[
{id:'aprendiz',levelId:'aprendiz',order:1,directory:'common/',priceFactor:1},
{id:'explorador',levelId:'explorador',order:2,directory:'',priceFactor:4},
{id:'aventurero',levelId:'aventurero',order:3,directory:'eclipse_aureo/',priceFactor:1}];
const EQUIPMENT_PIECES=[
{key:'helmet',asset:'nova_helmet',label:'Casco',slot:'helmet',basePrice:54,description:'Protección ligera para las primeras misiones.'},
{key:'chest',asset:'nova_chest',label:'Peto',slot:'chest',basePrice:48,description:'Protección frontal equilibrada.'},
{key:'shoulders',asset:'nova_shoulders',label:'Hombreras',slot:'shoulders',basePrice:38,description:'Protección de hombros preparada para la aventura.'},
{key:'gloves',asset:'nova_gloves',label:'Guanteletes',slot:'gloves',basePrice:34,description:'Protección de manos para manejar el equipo.'},
{key:'legs',asset:'nova_legs',label:'Grebas',slot:'legs',basePrice:44,description:'Protección articulada para moverse con confianza.'},
{key:'boots',asset:'nova_boots',label:'Botas',slot:'boots',basePrice:30,description:'Botas resistentes para explorar nuevos lugares.'},
{key:'shield',asset:'nova_shield',label:'Escudo',slot:'shield',basePrice:58,description:'Escudo equilibrado para protegerse.'},
{key:'weapon',asset:'nova_weapon',label:'Espada',slot:'weapon',basePrice:64,description:'Hoja de energía estable para las misiones.'}];
const ECLIPSE_PIECES=[
['helmet','eclipse_helmet','Casco Eclipse Áureo','helmet',320,'Casco de obsidiana estelar con líneas de oro.'],['chest','eclipse_chest','Peto Eclipse Áureo','chest',300,'Armadura negra reforzada con núcleo dorado.'],['shoulders','eclipse_shoulders','Hombreras Eclipse Áureo','shoulders',260,'Hombreras de obsidiana con bordes dorados.'],['gloves','eclipse_gloves','Guanteletes Eclipse Áureo','gloves',240,'Guanteletes negros con conductos de energía dorada.'],['legs','eclipse_legs','Grebas Eclipse Áureo','legs',280,'Grebas articuladas oscuras con refuerzos áureos.'],['boots','eclipse_boots','Botas Eclipse Áureo','boots',220,'Botas de gravedad negras con estabilizadores dorados.'],['shield','eclipse_shield','Escudo Eclipse Áureo','shield',340,'Escudo de obsidiana y oro.'],['weapon','eclipse_cannon','Cañón Eclipse Áureo','weapon',380,'Cañón estelar de gran tamaño.']].map(x=>({key:x[0],id:x[1],name:x[2],slot:x[3],price:x[4],asset:x[1],description:x[5]}));
const FELINE_PIECES=[
['helmet','Casco de Explorador Felino',55,'Casco ligero de aventurero con visor y detalles en bronce.'],['neck','Bufanda del Explorador',35,'Bufanda de viaje turquesa, cómoda y resistente.'],['shoulders','Hombreras del Explorador',48,'Hombreras reforzadas con el emblema de la brújula.'],['chest','Peto del Explorador',58,'Peto ligero con correas, bolsillos y protección.'],['gloves','Guanteletes del Explorador',44,'Guanteletes articulados para proteger las patas.'],['accessory','Bolsa y Brújula',42,'Bolsa de exploración con brújula.'],['legs','Pantalones del Explorador',46,'Pantalones resistentes para largas caminatas.'],['boots','Botas del Explorador',52,'Botas reforzadas para recorrer cualquier camino.'],['tail','Cola Felina',25,'Cola del personaje felino integrada como capa trasera.']].map(x=>({key:x[0],id:`felino_aprendiz_${x[0]}`,name:x[1],slot:x[0],price:x[2],asset:x[0],description:x[3]}));
const AVATAR={schemaVersion:8,canvas:{width:1024,height:1024},levels:AVATAR_LEVELS,base:{id:'avatar_base',src:'assets/avatar/base/avatar_base.png',layer:10,optional:false},slots:{back:{layer:0,label:'Espalda'},tail:{layer:5,label:'Cola'},legs:{layer:20,label:'Piernas'},boots:{layer:30,label:'Botas'},chest:{layer:40,label:'Pecho'},neck:{layer:45,label:'Cuello'},shoulders:{layer:50,label:'Hombreras'},gloves:{layer:60,label:'Brazos y guantes'},head:{layer:70,label:'Cabeza'},helmet:{layer:80,label:'Casco'},accessory:{layer:85,label:'Accesorio'},shield:{layer:90,label:'Escudo'},weapon:{layer:100,label:'Arma'},effects:{layer:110,label:'Efectos'}},economy:{defaultPriceMultiplier:1,minimumPriceMultiplier:.25,maximumPriceMultiplier:3},characters:{principal:{id:'principal',name:'Avatar principal',description:'Avatar principal disponible.',levelId:'aventurero',masterSrc:'assets/avatar/base/avatar_base.png',price:0,available:true,assetStatus:'available'},personaje_femenino:{id:'personaje_femenino',name:'Personaje femenino',description:'Pendiente de avatar maestro aprobado.',levelId:'aprendiz',masterSrc:null,price:250,available:false,assetStatus:'pending_asset'},personaje_animal:{id:'personaje_animal',name:'Felino',description:'Personaje felino aventurero · Categoría 1.',levelId:'aprendiz',masterSrc:'assets/avatar/base/felino_aprendiz.png',price:350,available:true,assetStatus:'available',categoryIds:['felino_aprendiz']}},items:[]};
AVATAR.items=[...EQUIPMENT_TIERS.slice(0,2).flatMap(t=>EQUIPMENT_PIECES.map(p=>({id:`${p.asset}_${t.id}`,name:`${p.label} ${LEVEL_BY_ID[t.levelId].name}`,description:p.description,slot:p.slot,levelId:t.levelId,level:t.order,price:p.basePrice*t.priceFactor,characterId:'principal',shopImage:`assets/shop/nova_guardian/${t.directory}${p.asset}.png`,avatarLayer:`assets/avatar/equipment/nova_guardian/${t.directory}${p.asset}.png`,available:true}))),...ECLIPSE_PIECES.map(p=>({id:p.id,name:p.name,description:p.description,slot:p.slot,levelId:'aventurero',level:3,price:p.price,characterId:'principal',shopImage:`assets/shop/eclipse_aureo/${p.asset}.png`,avatarLayer:`assets/avatar/equipment/eclipse_aureo/${p.asset}.png`,available:true})),...FELINE_PIECES.map(p=>({id:p.id,name:p.name,description:p.description,slot:p.slot,levelId:'aprendiz',level:1,categoryId:'felino_aprendiz',characterId:'personaje_animal',price:p.price,shopImage:`assets/shop/felino/aprendiz/${p.asset}.png`,avatarLayer:`assets/avatar/equipment/felino/aprendiz/${p.asset}.png`,available:true}))];
window.AVATAR_LEVELS=AVATAR_LEVELS;window.LEVEL_BY_ID=LEVEL_BY_ID;window.LEVEL_BY_ORDER=LEVEL_BY_ORDER;
