(function(){
  'use strict';
  const VALID_SLOTS=Object.keys(AVATAR.slots);
  function getItem(id){return AVATAR.items.find(item=>item.id===id)||null;}
  function getAvatarLevel(data,characterId){const state=data?.avatar?.characters?.[characterId];return Math.max(1,Number(state?.level)||1);}
  function isItemCompatibleWithLevel(data,item,characterId){return !!item&&Number(item.level)<=getAvatarLevel(data,characterId);}
  function validateItem(item){const errors=[];if(!item||typeof item!=='object')return['Objeto no válido'];if(!item.id||typeof item.id!=='string')errors.push('Falta id');if(!VALID_SLOTS.includes(item.slot))errors.push(`Slot no válido: ${item.slot}`);if(!item.avatarLayer||typeof item.avatarLayer!=='string')errors.push('Falta avatarLayer');if(!Number.isFinite(Number(item.price))||Number(item.price)<0)errors.push('Precio no válido');if(!Number.isInteger(Number(item.level))||Number(item.level)<1||Number(item.level)>8)errors.push('Nivel no válido');if(!item.levelId||!LEVEL_BY_ID[item.levelId]||LEVEL_BY_ID[item.levelId].order!==Number(item.level))errors.push('Nivel incoherente');if('x' in item||'y' in item||'scale' in item||'rotation' in item)errors.push('No se permiten ajustes de posición, escala o rotación por objeto');return errors;}
  function validateCatalog(){const seen=new Set(),problems=[];for(const item of AVATAR.items){const errors=validateItem(item);if(seen.has(item.id))errors.push('ID duplicado');seen.add(item.id);if(errors.length)problems.push({id:item.id||'(sin id)',errors});}return problems;}
  function ensureState(data){if(!data.avatar)data.avatar={owned:[],equipped:{}};if(!data.avatar.characters)data.avatar.characters={};if(!data.avatar.characters.principal)data.avatar.characters.principal={unlocked:true,level:3,levelId:'aventurero',owned:[],equipped:{}};for(const id of Object.keys(AVATAR.characters||{}))if(!data.avatar.characters[id])data.avatar.characters[id]={unlocked:false,level:Math.max(1,Number(AVATAR.characters[id].levelId==='aventurero'?3:1)),levelId:AVATAR.characters[id].levelId||'aprendiz',owned:[],equipped:{}};if(!data.avatar.activeCharacterId||!data.avatar.characters[data.avatar.activeCharacterId]?.unlocked)data.avatar.activeCharacterId='principal';for(const state of Object.values(data.avatar.characters)){if(!Array.isArray(state.owned))state.owned=[];if(!state.equipped||typeof state.equipped!=='object')state.equipped={};for(const slot of VALID_SLOTS)if(!(slot in state.equipped))state.equipped[slot]=null;state.level=Math.min(8,Math.max(1,Number(state.level)||1));state.levelId=LEVEL_BY_ORDER[state.level]?.id||'aprendiz';state.owned=[...new Set(state.owned.filter(id=>{const item=getItem(id);return item&&item.available!==false&&item.characterId===Object.keys(data.avatar.characters).find(cid=>data.avatar.characters[cid]===state)}))];for(const slot of VALID_SLOTS){const item=getItem(state.equipped[slot]);if(!item||item.slot!==slot||!isItemCompatibleWithLevel(data,item,Object.keys(data.avatar.characters).find(cid=>data.avatar.characters[cid]===state)))state.equipped[slot]=null;}}const active=data.avatar.characters[data.avatar.activeCharacterId];data.avatar.owned=[...active.owned];data.avatar.equipped={...active.equipped};return data.avatar;}
  function owns(data,itemId){return ensureState(data).owned.includes(itemId);}
  function grant(data,itemId){const item=getItem(itemId);if(!item)throw new Error(`Objeto de avatar desconocido: ${itemId}`);const avatar=ensureState(data);if(!avatar.owned.includes(itemId))avatar.owned.push(itemId);return true;}
  function priceFor(data,itemOrId){const item=typeof itemOrId==='string'?getItem(itemOrId):itemOrId;if(!item)return 0;const configured=Number(data?.ajustes?.multiplicadorPrecios),fallback=Number(AVATAR.economy?.defaultPriceMultiplier)||1,minimum=Number(AVATAR.economy?.minimumPriceMultiplier)||.25,maximum=Number(AVATAR.economy?.maximumPriceMultiplier)||3;const multiplier=Math.min(maximum,Math.max(minimum,Number.isFinite(configured)?configured:fallback));return Math.max(1,Math.round((Number(item.price)||0)*multiplier));}
  function buy(data,itemId){const item=getItem(itemId);if(!item||item.available===false)throw new Error(`Objeto de avatar no disponible: ${itemId}`);const avatar=ensureState(data),characterId=item.characterId;const state=data.avatar.characters[characterId];if(!state?.unlocked)return{ok:false,reason:'character'};if(!isItemCompatibleWithLevel(data,item,characterId))return{ok:false,reason:'level',item};if(state.owned.includes(itemId))return{ok:false,reason:'owned',item};const price=priceFor(data,item),diamonds=Math.max(0,Number(data.diamantes)||0);if(diamonds<price)return{ok:false,reason:'diamonds',item};data.diamantes=diamonds-price;state.owned.push(itemId);return{ok:true,item,spent:price};}
  function revoke(data,itemId){const avatar=ensureState(data);avatar.owned=avatar.owned.filter(id=>id!==itemId);for(const state of Object.values(avatar.characters))for(const slot of VALID_SLOTS)if(state.equipped[slot]===itemId)state.equipped[slot]=null;}
  function equip(data,itemId,{allowUnowned=false}={}){const item=getItem(itemId);if(!item)throw new Error(`Objeto de avatar desconocido: ${itemId}`);const errors=validateItem(item);if(errors.length)throw new Error(`${itemId}: ${errors.join(', ')}`);if(!item.available&&item.level>getAvatarLevel(data,item.characterId))return{ok:false,reason:'level',item};const avatar=ensureState(data),state=data.avatar.characters[item.characterId];if(!state)return{ok:false,reason:'character'};if(!isItemCompatibleWithLevel(data,item,item.characterId))return{ok:false,reason:'level',item};if(!allowUnowned&&!state.owned.includes(itemId))return{ok:false,reason:'unowned'};state.equipped[item.slot]=itemId;data.avatar.activeCharacterId=item.characterId;data.avatar.owned=[...state.owned];data.avatar.equipped={...state.equipped};return{ok:true,item};}
  function unequip(data,slot){if(!VALID_SLOTS.includes(slot))throw new Error(`Slot no válido: ${slot}`);const avatar=ensureState(data),state=data.avatar.characters[data.avatar.activeCharacterId];state.equipped[slot]=null;data.avatar.equipped={...state.equipped};}
  function equippedItems(data){const avatar=ensureState(data),state=data.avatar.characters[data.avatar.activeCharacterId];return VALID_SLOTS.map(slot=>getItem(state?.equipped[slot])).filter(Boolean).sort((a,b)=>AVATAR.slots[a.slot].layer-AVATAR.slots[b.slot].layer);}
  function previewItems(data,previewItemId){const bySlot=new Map(equippedItems(data).map(item=>[item.slot,item]));const preview=getItem(previewItemId);if(preview&&isItemCompatibleWithLevel(data,preview,preview.characterId))bySlot.set(preview.slot,preview);return [...bySlot.values()].sort((a,b)=>AVATAR.slots[a.slot].layer-AVATAR.slots[b.slot].layer);}
  function assetURL(src){const version=window.APP_VERSION;if(!version)return src;return `${src}${src.includes('?')?'&':'?'}v=${encodeURIComponent(version)}`;}
  function makeLayer(src,layer,kind,id,levelId=''){const img=document.createElement('img');img.src=assetURL(src);img.alt='';img.draggable=false;img.className='avatar-layer';img.dataset.kind=kind;if(id)img.dataset.itemId=id;if(levelId)img.dataset.level=levelId;img.style.zIndex=String(layer);return img;}
  function render(container,data,{showBase=true,onAssetError=null,previewItemId=null,baseSrc=null}={}){if(typeof container==='string')container=document.querySelector(container);if(!container)throw new Error('No se encontró el contenedor del avatar');container.classList.add('avatar-stage');container.style.setProperty('--avatar-aspect',`${AVATAR.canvas.width}/${AVATAR.canvas.height}`);container.replaceChildren();const add=img=>{img.addEventListener('error',()=>{img.classList.add('avatar-asset-error');if(typeof onAssetError==='function')onAssetError(img.src,img.dataset.itemId||'base');},{once:true});container.appendChild(img);};const items=previewItemId?previewItems(data,previewItemId):equippedItems(data);if(showBase){const src=baseSrc||AVATAR.base.src;if(src)add(makeLayer(src,AVATAR.base.layer,'base',AVATAR.base.id));}for(const item of items)add(makeLayer(item.avatarLayer,AVATAR.slots[item.slot].layer,previewItemId===item.id?'preview':'equipment',item.id,item.levelId));return container;}
  function inspectImageDimensions(src){return new Promise(resolve=>{const img=new Image();img.onload=()=>resolve({src,ok:img.naturalWidth===AVATAR.canvas.width&&img.naturalHeight===AVATAR.canvas.height,width:img.naturalWidth,height:img.naturalHeight,expected:{...AVATAR.canvas}});img.onerror=()=>resolve({src,ok:false,error:'No se pudo cargar el recurso',expected:{...AVATAR.canvas}});img.src=assetURL(src);});}
  async function validateAssets({includeBase=true}={}){const checks=[];if(includeBase&&AVATAR.base.src)checks.push(inspectImageDimensions(AVATAR.base.src));for(const item of AVATAR.items.filter(item=>item.available!==false))checks.push(inspectImageDimensions(item.avatarLayer));return Promise.all(checks);}
  window.AvatarSystem={canvas:{...AVATAR.canvas},slots:{...AVATAR.slots},getItem,validateItem,validateCatalog,validateAssets,ensureState,owns,grant,priceFor,buy,revoke,equip,unequip,equippedItems,render,getAvatarLevel,isItemCompatibleWithLevel};
})();
