/** Catálogo único del avatar y su equipamiento paper-doll. */
const AVATAR_LEVELS=[{id:'aprendiz',name:'Aprendiz',order:1},{id:'explorador',name:'Explorador',order:2},{id:'aventurero',name:'Aventurero',order:3},{id:'guerrero',name:'Guerrero',order:4},{id:'heroe',name:'Héroe',order:5},{id:'campeon',name:'Campeón',order:6},{id:'maestro',name:'Maestro',order:7},{id:'leyenda',name:'Leyenda',order:8}];
const LEVEL_BY_ID=Object.fromEntries(AVATAR_LEVELS.map(x=>[x.id,x])),LEVEL_BY_ORDER=Object.fromEntries(AVATAR_LEVELS.map(x=>[x.order,x]));
const EQUIPMENT_TIERS=[{id:'aprendiz',levelId:'aprendiz',order:1,directory:'common/',priceFactor:1},{id:'explorador',levelId:'explorador',order:2,directory:'',priceFactor:4},{id:'aventurero',levelId:'aventurero',order:3,directory:'eclipse_aureo/',priceFactor:1}];
const EQUIPMENT_PIECES=[['helmet','Casco','nova_helmet',54],['chest','Peto','nova_chest',48],['shoulders','Hombreras','nova_shoulders',38],['gloves','Guanteletes','nova_gloves',34],['legs','Grebas','nova_legs',44],['boots','Botas','nova_boots',30],['shield','Escudo','nova_shield',58],['weapon','Espada','nova_weapon',64]].map(x=>({slot:x[0],label:x[1],asset:x[2],basePrice:x[3]}));
const ECLIPSE_PIECES=[['helmet','eclipse_helmet','Casco Eclipse Áureo','helmet',320],['chest','eclipse_chest','Peto Eclipse Áureo','chest',300],['shoulders','eclipse_shoulders','Hombreras Eclipse Áureo','shoulders',260],['gloves','eclipse_gloves','Guanteletes Eclipse Áureo','gloves',240],['legs','eclipse_legs','Grebas Eclipse Áureo','legs',280],['boots','eclipse_boots','Botas Eclipse Áureo','boots',220],['shield','eclipse_shield','Escudo Eclipse Áureo','shield',340],['weapon','eclipse_cannon','Cañón Eclipse Áureo','weapon',380]].map(x=>({key:x[0],id:x[1],name:x[2],slot:x[3],price:x[4],asset:x[1]}));
const AVATAR={schemaVersion:10,canvas:{width:1024,height:1024},levels:AVATAR_LEVELS,base:{id:'avatar_base',src:'assets/avatar/base/avatar_base.png',layer:10,optional:false},slots:{back:{layer:0,label:'Espalda'},tail:{layer:5,label:'Cola'},legs:{layer:20,label:'Piernas'},boots:{layer:30,label:'Botas'},chest:{layer:40,label:'Pecho'},neck:{layer:45,label:'Cuello'},shoulders:{layer:50,label:'Hombreras'},gloves:{layer:60,label:'Brazos y guantes'},head:{layer:70,label:'Cabeza'},helmet:{layer:80,label:'Casco'},accessory:{layer:85,label:'Accesorio'},shield:{layer:90,label:'Escudo'},weapon:{layer:100,label:'Arma'},effects:{layer:110,label:'Efectos'}},economy:{defaultPriceMultiplier:1,minimumPriceMultiplier:.25,maximumPriceMultiplier:3},characters:{principal:{id:'principal',name:'Avatar principal',description:'Avatar principal disponible.',levelId:'aventurero',masterSrc:'assets/avatar/base/avatar_base.png',price:0,available:true,assetStatus:'available'}},items:[]};
AVATAR.items=[...EQUIPMENT_TIERS.slice(0,2).flatMap(t=>EQUIPMENT_PIECES.map(p=>({id:`${p.asset}_${t.id}`,name:`${p.label} ${LEVEL_BY_ID[t.levelId].name}`,description:`${p.label} del nivel ${LEVEL_BY_ID[t.levelId].name}.`,slot:p.slot,levelId:t.levelId,level:t.order,price:p.basePrice*t.priceFactor,characterId:'principal',shopImage:`assets/shop/nova_guardian/${t.directory}${p.asset}.png`,avatarLayer:`assets/avatar/equipment/nova_guardian/${t.directory}${p.asset}.png`,available:true}))),...ECLIPSE_PIECES.map(p=>({id:p.id,name:p.name,description:`${p.name}, equipamiento de élite.`,slot:p.slot,levelId:'aventurero',level:3,price:p.price,characterId:'principal',shopImage:`assets/shop/eclipse_aureo/${p.asset}.png`,avatarLayer:`assets/avatar/equipment/eclipse_aureo/${p.asset}.png`,available:true}))];
window.AVATAR_LEVELS=AVATAR_LEVELS;window.LEVEL_BY_ID=LEVEL_BY_ID;window.LEVEL_BY_ORDER=LEVEL_BY_ORDER;
