/* Tank Pixel · duelo 2 jugadores · colisiones, proyectiles y bonus */
(()=>{
const SID='tank-pixel-style',CARD='tank-pixel-home-card';let home0=null;
const css=()=>{if(document.getElementById(SID))return;const l=document.createElement('link');l.id=SID;l.rel='stylesheet';l.href='css/tank-pixel.css?v='+(window.APP_VERSION||Date.now());document.head.appendChild(l)};
const unlocked=()=>typeof window.actionGamesAvailable==='function'&&window.actionGamesAvailable();
function card(){const g=document.querySelector('.action-game-grid');if(!g||g.querySelector('.'+CARD))return;const ok=unlocked(),b=document.createElement('button');b.type='button';b.className='guardian-home-card planet-home-card '+CARD+' '+(ok?'unlocked':'locked');b.disabled=!ok;b.setAttribute('aria-disabled',String(!ok));b.innerHTML=`<span class="guardian-home-icon">${ok?'🎯':'🔒'}</span><span><b>Tank Pixel</b><small>${ok?'Duelo de tanques para dos jugadores':'Completa los retos de hoy para desbloquear una partida'}</small></span><strong>${ok?'JUGAR →':'BLOQUEADO'}</strong>`;if(ok)b.onclick=open;g.appendChild(b)}
function hook(){css();if(typeof window.home==='function'&&!window.home.__tankPixelHooked){home0=window.home;const w=function(){const r=home0.apply(this,arguments);requestAnimationFrame(card);return r};w.__tankPixelHooked=true;window.home=w}requestAnimationFrame(card)}
function open(){if(!unlocked()){home();return}const A=document.getElementById('app');if(!A)return;document.body.classList.add('tank-pixel-active');A.innerHTML='<main class="tank2-screen"><div class="tank2-hud"><button id="tankBack">← SALIR</button><b>TANK PIXEL · 2 JUGADORES</b><span id="tankInfo">❤️ 5 : 5</span><button id="tankReset">↻</button></div><div class="tank2-arena-wrap"><canvas id="tankCanvas" width="1600" height="900"></canvas><div class="tank2-help"><span>🟢 J1 · joystick izquierdo</span><span>🔴 J2 · joystick derecho</span></div><div id="joy1" class="tank-joy"><i></i></div><div id="joy2" class="tank-joy"><i></i></div></div></main>';document.getElementById('tankBack').onclick=()=>{document.body.classList.remove('tank-pixel-active');window.home()};start()}
function start(){const c=document.getElementById('tankCanvas');if(!c)return;const x=c.getContext('2d');x.imageSmoothingEnabled=false;const W=c.width,H=c.height,TANK_R=34,EDGE=45;let raf,last=performance.now(),over=false,scores=[0,0],spawn=2;
const ps=[{x:170,y:H/2,ang:0,hp:5,cd:0,joy:{x:0,y:0},bonus:null,bonusT:0,shield:0,bounces:0},{x:W-170,y:H/2,ang:Math.PI,hp:5,cd:0,joy:{x:0,y:0},bonus:null,bonusT:0,shield:0,bounces:0}];
const obs=[{x:420,y:95,w:175,h:55,hp:7,max:7},{x:705,y:75,w:195,h:65,hp:9,max:9},{x:1020,y:105,w:175,h:55,hp:7,max:7},{x:350,y:285,w:175,h:65,hp:8,max:8},{x:635,y:240,w:125,h:90,hp:7,max:7},{x:855,y:295,w:195,h:65,hp:9,max:9},{x:1140,y:265,w:155,h:80,hp:7,max:7},{x:420,y:500,w:155,h:65,hp:7,max:7},{x:690,y:465,w:205,h:70,hp:9,max:9},{x:1035,y:495,w:155,h:65,hp:7,max:7},{x:225,y:700,w:195,h:60,hp:8,max:8},{x:590,y:675,w:155,h:70,hp:7,max:7},{x:900,y:705,w:185,h:60,hp:8,max:8},{x:1190,y:665,w:185,h:70,hp:9,max:9}];
const parts=[],bul=[],bon=[];
const TYPES={rapid:{icon:'⚡',name:'CADENCIA',color:'#ffe066',duration:7},shield:{icon:'🛡️',name:'ESCUDO',color:'#72d9ff',duration:9},power:{icon:'💥',name:'POTENCIA',color:'#ff765f',duration:8},speed:{icon:'🚀',name:'TURBO',color:'#70ef9a',duration:7},double:{icon:'✦',name:'DOBLE DISPARO',color:'#d69cff',duration:7},repair:{icon:'✚',name:'REPARACIÓN',color:'#9dff8c',duration:0},bounce:{icon:'↔',name:'REBOTE EXTRA',color:'#ffb35c',duration:10}};
function circleRect(cx,cy,r,o){const nx=Math.max(o.x,Math.min(cx,o.x+o.w)),ny=Math.max(o.y,Math.min(cy,o.y+o.h));return (cx-nx)**2+(cy-ny)**2<r*r}
function resolveTank(p,oldX,oldY){for(const o of obs){if(o.hp<=0)continue;let nx=Math.max(o.x,Math.min(p.x,o.x+o.w)),ny=Math.max(o.y,Math.min(p.y,o.y+o.h)),dx=p.x-nx,dy=p.y-ny,d2=dx*dx+dy*dy;if(d2<TANK_R*TANK_R){if(d2>0){const d=Math.sqrt(d2),push=TANK_R-d;p.x+=dx/d*push;p.y+=dy/d*push}else{const l=Math.abs(p.x-o.x),r=Math.abs(p.x-(o.x+o.w)),t=Math.abs(p.y-o.y),b=Math.abs(p.y-(o.y+o.h)),m=Math.min(l,r,t,b);if(m===l)p.x=o.x-TANK_R;else if(m===r)p.x=o.x+o.w+TANK_R;else if(m===t)p.y=o.y-TANK_R;else p.y=o.y+o.h+TANK_R}}
}p.x=Math.max(EDGE,Math.min(W-EDGE,p.x));p.y=Math.max(EDGE,Math.min(H-EDGE,p.y));
/* segunda pasada: corrige cualquier contacto residual sin congelar el tanque */
for(const o of obs)if(o.hp>0&&circleRect(p.x,p.y,TANK_R,o)){p.x=oldX;p.y=oldY;break}}
function fx(a,b,n=10){for(let i=0;i<n;i++)parts.push({x:a,y:b,vx:(Math.random()-.5)*240,vy:(Math.random()-.5)*240,t:.5})}
function damageTank(target,amount,owner){if(target.hp<=0)return;if(target.shield>0){target.shield--;fx(target.x,target.y,8);return}target.hp=Math.max(0,target.hp-amount);if(owner!==undefined)scores[owner]++;fx(target.x,target.y,14);if(target.hp<=0)over=true}
function fire(i){const p=ps[i];if(over||p.cd>0||p.hp<=0)return;const rapid=p.bonus==='rapid',double=p.bonus==='double',power=p.bonus==='power';p.cd=rapid?.13:.30;const a=p.ang,off=double?.105:0;const make=(aa)=>bul.push({x:p.x+Math.cos(aa)*43,y:p.y+Math.sin(aa)*43,vx:Math.cos(aa)*690,vy:Math.sin(aa)*690,r:7,owner:i,damage:power?2:1,bounces:0,maxBounces:p.bonus==='bounce'?8:3,dead:false});make(a);if(double){make(a+off);make(a-off)}}
function joy(el,i){let id=null;const mv=e=>{if(id!==e.pointerId)return;const r=el.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),d=Math.hypot(dx,dy),m=Math.min(1,d/(r.width*.35));if(m>.12)ps[i].ang=Math.atan2(dy,dx);ps[i].joy=m>.12?{x:Math.cos(Math.atan2(dy,dx))*m,y:Math.sin(Math.atan2(dy,dx))*m}:{x:0,y:0};el.querySelector('i').style.transform=`translate(${ps[i].joy.x*38}px,${ps[i].joy.y*38}px)`};const end=e=>{if(id===e.pointerId){id=null;ps[i].joy={x:0,y:0};el.classList.remove('active');el.querySelector('i').style.transform='translate(0,0)'}};el.onpointerdown=e=>{id=e.pointerId;el.setPointerCapture(id);el.classList.add('active');mv(e)};el.onpointermove=mv;el.onpointerup=end;el.onpointercancel=end}joy(document.getElementById('joy1'),0);joy(document.getElementById('joy2'),1);
function spawnBonus(){if(bon.length>=2)return;const keys=Object.keys(TYPES),type=keys[Math.floor(Math.random()*keys.length)],b={x:250+Math.random()*1100,y:80+Math.random()*740,r:24,life:9,type};if(obs.some(o=>o.hp>0&&circleRect(b.x,b.y,b.r+15,o))||ps.some(p=>Math.hypot(p.x-b.x,p.y-b.y)<110)){return}if(!bon.some(z=>Math.hypot(z.x-b.x,z.y-b.y)<100))bon.push(b)}
function applyBonus(p,b){const q=TYPES[b.type];p.bonus=b.type;p.bonusT=q.duration;if(b.type==='shield')p.shield=3;if(b.type==='repair')p.hp=Math.min(5,p.hp+2);if(b.type==='bounce')p.bounces=8}
function updateBullet(b,dt){b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x-b.r<=0){b.x=b.r;b.vx=Math.abs(b.vx);b.bounces++}else if(b.x+b.r>=W){b.x=W-b.r;b.vx=-Math.abs(b.vx);b.bounces++}if(b.y-b.r<=0){b.y=b.r;b.vy=Math.abs(b.vy);b.bounces++}if(b.y-b.r>H){b.dead=true;return}if(b.bounces>b.maxBounces){b.dead=true;return}for(const o of obs)if(o.hp>0&&circleRect(b.x,b.y,b.r,o)){o.hp=Math.max(0,o.hp-b.damage);b.dead=true;fx(b.x,b.y,o.hp?8:24);return}for(let i=0;i<2;i++)if(i!==b.owner&&ps[i].hp>0&&Math.hypot(ps[i].x-b.x,ps[i].y-b.y)<TANK_R+b.r){b.dead=true;damageTank(ps[i],b.damage,b.owner);return}}
function drawTank(p,i){x.save();x.translate(Math.round(p.x),Math.round(p.y));x.rotate(p.ang);x.fillStyle=i?'#a93246':'#1eaa63';x.fillRect(-38,-28,76,56);x.fillStyle='#18232c';x.fillRect(-44,-22,10,15);x.fillRect(34,-22,10,15);x.fillRect(-44,7,10,15);x.fillRect(34,7,10,15);x.fillStyle=i?'#ff6f7d':'#54ee91';x.fillRect(-21,-21,42,42);x.fillStyle='#111b24';x.fillRect(0,-8,55,16);x.fillStyle='#e8fbff';x.fillRect(40,-4,14,8);if(p.shield>0){x.strokeStyle='#70dfff';x.lineWidth=5;x.beginPath();x.arc(0,0,48,0,Math.PI*2);x.stroke()}x.restore()}
function drawObstacle(o){if(o.hp<=0)return;x.fillStyle='#34434e';x.fillRect(o.x,o.y,o.w,o.h);x.fillStyle='#657683';for(let yy=o.y+5;yy<o.y+o.h-8;yy+=16)for(let xx=o.x+5;xx<o.x+o.w-8;xx+=24){x.fillRect(xx,yy,18,10);x.fillStyle='#81909b';x.fillRect(xx+2,yy+2,14,3);x.fillStyle='#657683'}x.fillStyle='#202a33';x.fillRect(o.x,o.y+o.h-8,o.w,8);x.fillStyle='#f1c64c';x.fillRect(o.x,o.y-7,o.w*o.hp/o.max,4)}
function draw(){x.fillStyle='#07111a';x.fillRect(0,0,W,H);x.fillStyle='#0e202d';for(let y=0;y<H;y+=40)for(let z=0;z<W;z+=40)x.fillRect(z,y,2,2);x.strokeStyle='#29465a';x.lineWidth=6;x.strokeRect(3,3,W-6,H-6);x.strokeStyle='#193246';x.lineWidth=2;x.beginPath();x.moveTo(W/2,0);x.lineTo(W/2,H);x.stroke();obs.forEach(drawObstacle);bon.forEach(b=>{const q=TYPES[b.type];x.strokeStyle=q.color;x.lineWidth=4;x.beginPath();x.arc(b.x,b.y,b.r+6,0,Math.PI*2);x.stroke();x.font='31px sans-serif';x.textAlign='center';x.fillText(q.icon,b.x,b.y+10);x.fillStyle='#fff';x.font='bold 12px monospace';x.fillText(q.name,b.x,b.y+42)});ps.forEach((p,i)=>{if(p.hp>0)drawTank(p,i)});bul.forEach(b=>{x.fillStyle=b.owner?'#ff6b76':'#ffe06b';x.fillRect(Math.round(b.x-6),Math.round(b.y-6),12,12)});parts.forEach(s=>{x.fillStyle='#ffd45a';x.fillRect(s.x-2,s.y-2,4,4)});const active=ps.map((p,i)=>p.bonus?`J${i+1}: ${TYPES[p.bonus].icon} ${TYPES[p.bonus].name} ${Math.ceil(p.bonusT)}s`:'').filter(Boolean).join('   ');document.getElementById('tankInfo').textContent=`❤️ ${ps[0].hp} : ${ps[1].hp}   💥 ${scores[0]}-${scores[1]}${active?'   '+active:''}`;if(over){x.fillStyle='rgba(0,0,0,.76)';x.fillRect(0,0,W,H);x.textAlign='center';x.fillStyle='#fff';x.font='bold 50px monospace';x.fillText(ps[0].hp<=0?'¡GANA JUGADOR 2!':'¡GANA JUGADOR 1!',W/2,H/2);x.font='bold 22px monospace';x.fillText('Pulsa ↻ para volver a jugar',W/2,H/2+48)}}
function loop(now){const dt=Math.min(.032,(now-last)/1000);last=now;if(!over){ps.forEach((p,i)=>{p.cd=Math.max(0,p.cd-dt);if(p.bonusT>0){p.bonusT-=dt;if(p.bonusT<=0){p.bonus=null;p.shield=0;p.bounces=0}}const ox=p.x,oy=p.y,boost=p.bonus==='speed'?390:250;p.x+=p.joy.x*boost*dt;p.y+=p.joy.y*boost*dt;resolveTank(p,ox,oy);if(Math.hypot(p.joy.x,p.joy.y)>.15)fire(i)});bul.forEach(b=>updateBullet(b,dt));for(let i=bul.length-1;i>=0;i--)if(bul[i].dead)bul.splice(i,1);bon.forEach(b=>b.life-=dt);for(let i=bon.length-1;i>=0;i--){if(bon[i].life<=0){bon.splice(i,1);continue}for(const p of ps)if(p.hp>0&&Math.hypot(p.x-bon[i].x,p.y-bon[i].y)<TANK_R+b.r){applyBonus(p,bon[i]);fx(bon[i].x,bon[i].y,18);bon.splice(i,1);break}}spawn-=dt;if(spawn<=0){spawnBonus();spawn=5.5+Math.random()*4.5}parts.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.t-=dt});for(let i=parts.length-1;i>=0;i--)if(parts[i].t<=0)parts.splice(i,1)}draw();raf=requestAnimationFrame(loop)}requestAnimationFrame(loop);document.getElementById('tankReset').onclick=()=>{cancelAnimationFrame(raf);open()}}
css();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook,{once:true});else hook();
})();
