/* Tank Pixel · duelo 2 jugadores */
(()=>{
const SID='tank-pixel-style',CARD='tank-pixel-home-card';let home0=null;
const css=()=>{if(document.getElementById(SID))return;const l=document.createElement('link');l.id=SID;l.rel='stylesheet';l.href='css/tank-pixel.css?v='+(window.APP_VERSION||Date.now());document.head.appendChild(l)};
const unlocked=()=>typeof window.actionGamesAvailable==='function'&&window.actionGamesAvailable();
function card(){const g=document.querySelector('.action-game-grid');if(!g||g.querySelector('.'+CARD))return;const ok=unlocked(),b=document.createElement('button');b.type='button';b.className='guardian-home-card planet-home-card '+CARD+' '+(ok?'unlocked':'locked');b.disabled=!ok;b.setAttribute('aria-disabled',String(!ok));b.innerHTML=`<span class="guardian-home-icon">${ok?'🎯':'🔒'}</span><span><b>Tank Pixel</b><small>${ok?'Duelo de tanques para dos jugadores':'Completa los retos de hoy para desbloquear una partida'}</small></span><strong>${ok?'JUGAR →':'BLOQUEADO'}</strong>`;if(ok)b.onclick=open;g.appendChild(b)}
function hook(){css();if(typeof window.home==='function'&&!window.home.__tankPixelHooked){home0=window.home;const w=function(){const r=home0.apply(this,arguments);requestAnimationFrame(card);return r};w.__tankPixelHooked=true;window.home=w}requestAnimationFrame(card)}
function open(){if(!unlocked()){home();return}const A=document.getElementById('app');if(!A)return;document.body.classList.add('tank-pixel-active');A.innerHTML='<main class="tank2-screen"><div class="tank2-hud"><button id="tankBack">← SALIR</button><b>TANK PIXEL · 2 JUGADORES</b><span id="tankInfo">💥 0 — 0</span><button id="tankReset">↻</button></div><div class="tank2-arena-wrap"><canvas id="tankCanvas" width="1600" height="900"></canvas><div class="tank2-help"><span>🟢 JUGADOR 1 · joystick izquierdo</span><span>🔴 JUGADOR 2 · joystick derecho</span></div><div id="joy1" class="tank-joy"><i></i></div><div id="joy2" class="tank-joy"><i></i></div></div></main>';document.getElementById('tankBack').onclick=()=>window.home();start()}
function start(){const c=document.getElementById('tankCanvas');if(!c)return;const x=c.getContext('2d');x.imageSmoothingEnabled=false;const W=c.width,H=c.height;let raf,last=performance.now(),over=false,scores=[0,0];const ps=[{x:180,y:H/2,ang:0,hp:5,cd:0,joy:{x:0,y:0}},{x:W-180,y:H/2,ang:Math.PI,hp:5,cd:0,joy:{x:0,y:0}}],bul=[],parts=[],bon=[];
const obs=[{x:420,y:100,w:170,h:50,hp:5,max:5},{x:700,y:80,w:190,h:60,hp:7,max:7},{x:1010,y:110,w:170,h:50,hp:5,max:5},{x:350,y:290,w:170,h:60,hp:6,max:6},{x:630,y:250,w:120,h:85,hp:5,max:5},{x:850,y:300,w:190,h:60,hp:7,max:7},{x:1140,y:270,w:150,h:75,hp:5,max:5},{x:430,y:500,w:150,h:60,hp:5,max:5},{x:690,y:470,w:200,h:65,hp:7,max:7},{x:1030,y:500,w:150,h:60,hp:5,max:5},{x:230,y:700,w:190,h:55,hp:6,max:6},{x:590,y:680,w:150,h:65,hp:5,max:5},{x:900,y:710,w:180,h:55,hp:6,max:6},{x:1190,y:670,w:180,h:65,hp:7,max:7}];let spawn=2;
function rect(r,b){const nx=Math.max(r.x,Math.min(b.x,r.x+r.w)),ny=Math.max(r.y,Math.min(b.y,r.y+r.h));return(b.x-nx)**2+(b.y-ny)**2<=b.r*b.r}function tankHit(p,b){return Math.hypot(p.x-b.x,p.y-b.y)<b.r+30}function fx(a,b,n=8){for(let i=0;i<n;i++)parts.push({x:a,y:b,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,t:.45})}
function fire(i){const p=ps[i];if(over||p.cd>0||p.hp<=0)return;p.cd=.3;bul.push({x:p.x+Math.cos(p.ang)*38,y:p.y+Math.sin(p.ang)*38,vx:Math.cos(p.ang)*640,vy:Math.sin(p.ang)*640,r:7,owner:i})}
function joy(el,i){let id=null;const mv=e=>{if(id!==e.pointerId)return;const r=el.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.min(1,Math.hypot(dx,dy)/(r.width*.35));if(m>.12)ps[i].ang=Math.atan2(dy,dx);ps[i].joy={x:Math.cos(Math.atan2(dy,dx))*m,y:Math.sin(Math.atan2(dy,dx))*m};const k=el.querySelector('i');k.style.transform=`translate(${ps[i].joy.x*38}px,${ps[i].joy.y*38}px)`};const end=e=>{if(id===e.pointerId){id=null;ps[i].joy={x:0,y:0};el.classList.remove('active');el.querySelector('i').style.transform='translate(0,0)'}};el.onpointerdown=e=>{id=e.pointerId;el.setPointerCapture(id);el.classList.add('active');mv(e)};el.onpointermove=mv;el.onpointerup=end;el.onpointercancel=end}joy(document.getElementById('joy1'),0);joy(document.getElementById('joy2'),1);
function spawnBonus(){const ts=[['⚡','rapid'],['🛡️','shield'],['💥','power'],['🚀','speed']];const q=ts[Math.floor(Math.random()*ts.length)],b={x:270+Math.random()*1060,y:80+Math.random()*740,r:23,life:8,icon:q[0],type:q[1]};if(!bon.some(z=>Math.hypot(z.x-b.x,z.y-b.y)<90))bon.push(b)}
function updateBullet(b,dt){b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x-b.r<=0){b.x=b.r;b.vx=Math.abs(b.vx)}if(b.x+b.r>=W){b.x=W-b.r;b.vx=-Math.abs(b.vx)}if(b.y-b.r<=0){b.y=b.r;b.vy=Math.abs(b.vy)}if(b.y-b.r>H){b.dead=true;return}for(const o of obs)if(o.hp>0&&rect(o,b)){o.hp--;b.dead=true;fx(b.x,b.y);if(o.hp===0)fx(o.x+o.w/2,o.y+o.h/2,22);return}for(let i=0;i<2;i++)if(i!==b.owner&&ps[i].hp>0&&tankHit(ps[i],b)){b.dead=true;ps[i].hp--;scores[b.owner]++;fx(b.x,b.y,16);if(ps[i].hp<=0)over=true;return}}
function drawTank(p,i){x.save();x.translate(p.x,p.y);x.rotate(p.ang);x.fillStyle=i?'#e65363':'#36d67b';x.fillRect(-34,-25,68,50);x.fillStyle='#19232d';x.fillRect(-40,-20,10,14);x.fillRect(30,-20,10,14);x.fillRect(-40,6,10,14);x.fillRect(30,6,10,14);x.fillStyle=i?'#ff9ba1':'#9affbd';x.fillRect(-18,-18,36,36);x.fillStyle='#17242f';x.fillRect(0,-7,48,14);x.fillStyle='#d9fbff';x.fillRect(31,-3,12,6);x.restore()}
function draw(){x.fillStyle='#08111b';x.fillRect(0,0,W,H);x.fillStyle='#0d1d29';for(let y=0;y<H;y+=45)for(let z=0;z<W;z+=45)x.fillRect(z,y,1,1);x.strokeStyle='#294157';x.lineWidth=5;x.strokeRect(3,3,W-6,H-6);x.strokeStyle='#172d3e';x.lineWidth=2;x.beginPath();x.moveTo(W/2,0);x.lineTo(W/2,H);x.stroke();obs.forEach(o=>{if(o.hp<=0)return;x.fillStyle='#414f5b';x.fillRect(o.x,o.y,o.w,o.h);x.fillStyle='#71808d';x.fillRect(o.x+5,o.y+5,o.w-10,o.h-10);x.fillStyle='#202a33';x.fillRect(o.x,o.y+o.h-7,o.w,7);x.fillStyle='#f1c64c';x.fillRect(o.x,o.y-6,o.w*o.hp/o.max,4)});bon.forEach(b=>{x.strokeStyle='#f4d04d';x.lineWidth=4;x.beginPath();x.arc(b.x,b.y,b.r+5,0,Math.PI*2);x.stroke();x.font='30px sans-serif';x.textAlign='center';x.fillText(b.icon,b.x,b.y+10)});ps.forEach((p,i)=>{if(p.hp>0)drawTank(p,i)});bul.forEach(b=>{x.fillStyle=b.owner?'#ff6b76':'#ffe06b';x.fillRect(b.x-6,b.y-6,12,12)});parts.forEach(s=>{x.fillStyle='#ffd45a';x.fillRect(s.x-2,s.y-2,4,4)});document.getElementById('tankInfo').textContent=`💥 ${scores[0]} — ${scores[1]}   ❤️ ${ps[0].hp} : ${ps[1].hp}`;if(over){x.fillStyle='rgba(0,0,0,.72)';x.fillRect(0,0,W,H);x.textAlign='center';x.fillStyle='#fff';x.font='bold 48px monospace';x.fillText(ps[0].hp<=0?'¡GANA JUGADOR 2!':'¡GANA JUGADOR 1!',W/2,H/2)}}
function loop(now){const dt=Math.min(.032,(now-last)/1000);last=now;if(!over){ps.forEach((p,i)=>{p.cd=Math.max(0,p.cd-dt);p.x+=p.joy.x*250*dt;p.y+=p.joy.y*250*dt;p.x=Math.max(45,Math.min(W-45,p.x));p.y=Math.max(45,Math.min(H-45,p.y));if(Math.hypot(p.joy.x,p.joy.y)>.15)fire(i)});bul.forEach(b=>updateBullet(b,dt));for(let i=bul.length-1;i>=0;i--)if(bul[i].dead)bul.splice(i,1);bon.forEach(b=>b.life-=dt);for(let i=bon.length-1;i>=0;i--){if(bon[i].life<=0){bon.splice(i,1);continue}for(const p of ps)if(p.hp>0&&Math.hypot(p.x-bon[i].x,p.y-bon[i].y)<48){p.cd=Math.min(p.cd,.08);p.bonus=bon[i].type;bon.splice(i,1);break}}spawn-=dt;if(spawn<=0){spawnBonus();spawn=5+Math.random()*4}parts.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.t-=dt});for(let i=parts.length-1;i>=0;i--)if(parts[i].t<=0)parts.splice(i,1)}draw();raf=requestAnimationFrame(loop)}requestAnimationFrame(loop);document.getElementById('tankReset').onclick=()=>{cancelAnimationFrame(raf);open()}}
css();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook,{once:true});else hook();
})();