/* Tank Pixel · duelo 2 jugadores · V3.8.16 */
(()=>{
const SID='tank-pixel-style',CARD='tank-pixel-home-card';let home0=null;
const css=()=>{if(document.getElementById(SID))return;const l=document.createElement('link');l.id=SID;l.rel='stylesheet';l.href='css/tank-pixel.css?v='+(window.APP_VERSION||Date.now());document.head.appendChild(l)};
const unlocked=()=>typeof window.actionGamesAvailable==='function'&&window.actionGamesAvailable();
function card(){const g=document.querySelector('.action-game-grid');if(!g||g.querySelector('.'+CARD))return;const ok=unlocked(),b=document.createElement('button');b.type='button';b.className='guardian-home-card planet-home-card '+CARD+' '+(ok?'unlocked':'locked');b.disabled=!ok;b.setAttribute('aria-disabled',String(!ok));b.innerHTML=`<span class="guardian-home-icon">${ok?'🎯':'🔒'}</span><span><b>Tank Pixel</b><small>${ok?'Duelo de tanques para dos jugadores':'Completa los retos de hoy para desbloquear una partida'}</small></span><strong>${ok?'JUGAR →':'BLOQUEADO'}</strong>`;if(ok)b.onclick=()=>{if(typeof window.playTankFromAccess==='function')window.playTankFromAccess();else open()};g.appendChild(b)}
function hook(){css();if(typeof window.home==='function'&&!window.home.__tankPixelHooked){home0=window.home;const w=function(){const r=home0.apply(this,arguments);requestAnimationFrame(card);return r};w.__tankPixelHooked=true;window.home=w}requestAnimationFrame(card)}
function open(){if(!unlocked()){home();return}const A=document.getElementById('app');if(!A)return;document.body.classList.add('tank-pixel-active');A.innerHTML='<main class="tank2-screen"><div class="tank2-hud"><button id="tankBack">← SALIR</button><b>TANK PIXEL · 2 JUGADORES</b><span id="tankInfo">❤️ 7 : 7   🏆 0-0</span><button id="tankReset">↻</button></div><div class="tank2-arena-wrap"><canvas id="tankCanvas" width="1920" height="1080"></canvas><div class="tank2-help"><span>🟢 J1 · joystick izquierdo</span><span>🔴 J2 · joystick derecho</span></div><div id="joy1" class="tank-joy"><i></i></div><div id="joy2" class="tank-joy"><i></i></div></div></main>';document.getElementById('tankBack').onclick=()=>{document.body.classList.remove('tank-pixel-active');window.home()};start()}
function start(){const c=document.getElementById('tankCanvas');if(!c)return;const x=c.getContext('2d');x.imageSmoothingEnabled=false;const W=c.width,H=c.height,TANK_R=42,EDGE=TANK_R+12,MAX_HP=7;let raf,last=performance.now(),over=false,roundPause=0,pendingWinner=0,scores=[0,0],spawn=2;
const ps=[{x:150,y:H/2,ang:0,hp:MAX_HP,cd:0,joy:{x:0,y:0},bonus:null,bonusT:0,shield:0},{x:W-150,y:H/2,ang:Math.PI,hp:MAX_HP,cd:0,joy:{x:0,y:0},bonus:null,bonusT:0,shield:0}];
const obs=[
{x:300,y:100,w:230,h:70,hp:9,max:9},{x:650,y:70,w:250,h:90,hp:11,max:11},{x:1030,y:110,w:230,h:70,hp:9,max:9},{x:1370,y:80,w:230,h:85,hp:10,max:10},
{x:240,y:330,w:250,h:85,hp:10,max:10},{x:570,y:280,w:170,h:115,hp:9,max:9},{x:820,y:360,w:280,h:80,hp:12,max:12},{x:1190,y:300,w:190,h:120,hp:10,max:10},{x:1450,y:360,w:230,h:80,hp:10,max:10},
{x:300,y:590,w:230,h:75,hp:9,max:9},{x:650,y:650,w:250,h:90,hp:11,max:11},{x:1020,y:590,w:230,h:75,hp:9,max:9},{x:1370,y:650,w:240,h:90,hp:11,max:11}
];
const parts=[],bul=[],bon=[];
const TYPES={rapid:{icon:'⚡',name:'CADENCIA',color:'#ffe066',duration:7},shield:{icon:'🛡️',name:'ESCUDO',color:'#72d9ff',duration:9},power:{icon:'💥',name:'POTENCIA',color:'#ff765f',duration:8},speed:{icon:'🚀',name:'TURBO',color:'#70ef9a',duration:7},double:{icon:'✦',name:'DOBLE DISPARO',color:'#d69cff',duration:7},repair:{icon:'✚',name:'REPARACIÓN',color:'#9dff8c',duration:0},bounce:{icon:'↔',name:'REBOTE EXTRA',color:'#ffb35c',duration:10}};
function circleRect(cx,cy,r,o){const nx=Math.max(o.x,Math.min(cx,o.x+o.w)),ny=Math.max(o.y,Math.min(cy,o.y+o.h));return (cx-nx)**2+(cy-ny)**2<r*r}
function blocked(px,py){return obs.some(o=>o.hp>0&&circleRect(px,py,TANK_R+2,o))}
function moveTank(p,dt){const speed=p.bonus==='speed'?210:150;let dx=p.joy.x*speed*dt,dy=p.joy.y*speed*dt;const maxStep=6;const n=Math.max(1,Math.ceil(Math.max(Math.abs(dx),Math.abs(dy))/maxStep));dx/=n;dy/=n;
for(let s=0;s<n;s++){const nx=Math.max(EDGE,Math.min(W-EDGE,p.x+dx));if(!blocked(nx,p.y))p.x=nx;const ny=Math.max(EDGE,Math.min(H-EDGE,p.y+dy));if(!blocked(p.x,ny))p.y=ny}}
function explosion(px,py,big=false){const n=big?30:14;for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=(big?80:45)+Math.random()*140;parts.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s,t:.25+Math.random()*.45,kind:'spark',r:2+Math.random()*3})}for(let i=0;i<(big?7:3);i++)parts.push({x:px+(Math.random()-.5)*18,y:py+(Math.random()-.5)*18,vx:(Math.random()-.5)*30,vy:-20-Math.random()*45,t:.45+Math.random()*.5,kind:'smoke',r:7+Math.random()*10})}
function resetRound(){ps[0].x=150;ps[0].y=H/2;ps[0].ang=0;ps[1].x=W-150;ps[1].y=H/2;ps[1].ang=Math.PI;ps.forEach(p=>{p.hp=MAX_HP;p.cd=.45;p.joy={x:0,y:0};p.bonus=null;p.bonusT=0;p.shield=0});bul.length=0;bon.length=0;obs.forEach(o=>o.hp=o.max);spawn=2;roundPause=0;pendingWinner=0}
function damageTank(target,amount,owner){if(target.hp<=0||roundPause>0||over)return;if(target.shield>0){target.shield--;explosion(target.x,target.y);return}target.hp=Math.max(0,target.hp-amount);explosion(target.x,target.y,true);if(target.hp<=0&&owner!==undefined){scores[owner]++;pendingWinner=owner+1;if(scores[owner]>=2){over=true;return}roundPause=1.25;ps[0].joy={x:0,y:0};ps[1].joy={x:0,y:0};bul.length=0;bon.length=0}}
function fire(i){const p=ps[i];if(over||roundPause>0||p.cd>0||p.hp<=0)return;const rapid=p.bonus==='rapid',double=p.bonus==='double',power=p.bonus==='power';p.cd=rapid?.38:.78;const a=p.ang,off=double?.10:0;const make=(aa)=>{const sx=p.x+Math.cos(aa)*54,sy=p.y+Math.sin(aa)*54;explosion(sx,sy,false);bul.push({x:sx,y:sy,vx:Math.cos(aa)*520,vy:Math.sin(aa)*520,r:9,owner:i,damage:power?2:1,bounces:0,maxBounces:p.bonus==='bounce'?5:3,life:4.5,dead:false})};make(a);if(double){make(a-off);make(a+off)}}
function joy(el,i){let id=null;const update=(clientX,clientY)=>{const r=el.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=clientX-cx,dy=clientY-cy,d=Math.hypot(dx,dy),max=r.width*.39,m=Math.min(1,d/max);if(d>.08){ps[i].ang=Math.atan2(dy,dx);ps[i].joy={x:Math.cos(ps[i].ang)*m,y:Math.sin(ps[i].ang)*m};const k=el.querySelector('i'),km=Math.min(d,max);k.style.transform=`translate(${Math.cos(ps[i].ang)*km}px,${Math.sin(ps[i].ang)*km}px)`}};const down=e=>{id=e.pointerId;el.setPointerCapture(id);el.classList.add('active');update(e.clientX,e.clientY)};const move=e=>{if(id===e.pointerId)update(e.clientX,e.clientY)};const end=e=>{if(id===e.pointerId){id=null;ps[i].joy={x:0,y:0};el.classList.remove('active');el.querySelector('i').style.transform='translate(0,0)'}};el.onpointerdown=down;el.onpointermove=move;el.onpointerup=end;el.onpointercancel=end}
joy(document.getElementById('joy1'),0);joy(document.getElementById('joy2'),1);
function spawnBonus(){if(bon.length>=2)return;const keys=Object.keys(TYPES),type=keys[Math.floor(Math.random()*keys.length)],b={x:220+Math.random()*1480,y:100+Math.random()*880,r:28,life:9,type};if(obs.some(o=>o.hp>0&&circleRect(b.x,b.y,b.r+20,o))||ps.some(p=>Math.hypot(p.x-b.x,p.y-b.y)<130)||bon.some(z=>Math.hypot(z.x-b.x,z.y-b.y)<120))return;bon.push(b)}
function applyBonus(p,b){const q=TYPES[b.type];p.bonus=b.type;p.bonusT=q.duration;if(b.type==='shield')p.shield=3;if(b.type==='repair')p.hp=Math.min(MAX_HP,p.hp+2);if(b.type==='bounce')p.bounces=5}
function updateBullet(b,dt){b.life-=dt;if(b.life<=0){b.dead=true;return}b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x-b.r<=0){b.x=b.r;b.vx=Math.abs(b.vx);b.bounces++}else if(b.x+b.r>=W){b.x=W-b.r;b.vx=-Math.abs(b.vx);b.bounces++}if(b.y-b.r<=0){b.y=b.r;b.vy=Math.abs(b.vy);b.bounces++}if(b.y-b.r>H){b.dead=true;return}if(b.bounces>b.maxBounces){b.dead=true;return}for(const o of obs)if(o.hp>0&&circleRect(b.x,b.y,b.r,o)){o.hp=Math.max(0,o.hp-b.damage);b.dead=true;explosion(b.x,b.y,o.hp<=0);return}for(let i=0;i<2;i++)if(i!==b.owner&&ps[i].hp>0&&Math.hypot(ps[i].x-b.x,ps[i].y-b.y)<TANK_R+b.r){b.dead=true;damageTank(ps[i],b.damage,b.owner);return}}
function drawTank(p,i){x.save();x.translate(Math.round(p.x),Math.round(p.y));x.rotate(p.ang);x.fillStyle='#171a20';x.fillRect(-49,-34,98,68);x.fillStyle=i?'#a83246':'#218b58';x.fillRect(-43,-29,86,58);x.fillStyle='#2b3037';x.fillRect(-50,-25,12,17);x.fillRect(38,-25,12,17);x.fillRect(-50,8,12,17);x.fillRect(38,8,12,17);x.fillStyle=i?'#ef5b6b':'#43d982';x.fillRect(-25,-25,50,50);x.fillStyle='#10151b';x.fillRect(2,-10,65,20);x.fillStyle='#d9f7ff';x.fillRect(52,-4,15,8);x.fillStyle='#f2c94c';x.fillRect(-30,30,60,5);x.fillStyle='#20252b';x.fillRect(-25,-5,50,10);if(p.shield>0){x.strokeStyle='#73ddff';x.lineWidth=6;x.beginPath();x.arc(0,0,58,0,Math.PI*2);x.stroke()}x.restore()}
function drawObstacle(o){if(o.hp<=0)return;const damage=1-o.hp/o.max;x.fillStyle='#151b21';x.fillRect(o.x-6,o.y-6,o.w+12,o.h+12);x.fillStyle='#3d454d';x.fillRect(o.x,o.y,o.w,o.h);x.fillStyle='#59636b';for(let yy=o.y+6;yy<o.y+o.h-8;yy+=22)for(let xx=o.x+6;xx<o.x+o.w-8;xx+=30){x.fillRect(xx,yy,23,14);x.fillStyle='#77828a';x.fillRect(xx+3,yy+2,17,4);x.fillStyle='#59636b'}x.fillStyle='#252c32';x.fillRect(o.x,o.y+o.h-9,o.w,9);x.fillStyle='#c99a31';x.fillRect(o.x,o.y-8,o.w*o.hp/o.max,5);if(damage>.35){x.strokeStyle='rgba(20,20,20,.7)';x.lineWidth=4;x.beginPath();x.moveTo(o.x+20,o.y+20);x.lineTo(o.x+o.w*.45,o.y+o.h*.7);x.moveTo(o.x+o.w*.65,o.y+10);x.lineTo(o.x+o.w*.35,o.y+o.h*.85);x.stroke()}}
function drawBackground(){x.fillStyle='#081018';x.fillRect(0,0,W,H);x.strokeStyle='#102431';x.lineWidth=2;for(let z=0;z<W;z+=80){x.beginPath();x.moveTo(z,0);x.lineTo(z,H);x.stroke()}for(let y=0;y<H;y+=80){x.beginPath();x.moveTo(0,y);x.lineTo(W,y);x.stroke()}x.strokeStyle='#1b4052';x.lineWidth=5;x.strokeRect(14,14,W-28,H-28);x.strokeStyle='#123242';x.lineWidth=3;for(let y=120;y<H;y+=240){x.beginPath();x.moveTo(20,y);x.lineTo(180,y);x.lineTo(220,y+40);x.stroke();x.beginPath();x.moveTo(W-20,y+70);x.lineTo(W-180,y+70);x.lineTo(W-220,y+30);x.stroke()}x.fillStyle='#193444';for(let y=40;y<H;y+=160)for(let z=40;z<W;z+=160){x.fillRect(z,y,5,5);x.fillRect(z+9,y,5,5)}}
function draw(){drawBackground();x.strokeStyle='#31566a';x.lineWidth=4;x.beginPath();x.moveTo(W/2,30);x.lineTo(W/2,H-30);x.stroke();obs.forEach(drawObstacle);bon.forEach(b=>{const q=TYPES[b.type],pulse=1+Math.sin(performance.now()/120)*.12;x.strokeStyle=q.color;x.lineWidth=5;x.beginPath();x.arc(b.x,b.y,(b.r+7)*pulse,0,Math.PI*2);x.stroke();x.fillStyle='#101820';x.fillRect(b.x-30,b.y-30,60,60);x.font='34px sans-serif';x.textAlign='center';x.fillText(q.icon,b.x,b.y+11);x.fillStyle='#fff';x.font='bold 13px monospace';x.fillText(q.name,b.x,b.y+48)});ps.forEach((p,i)=>{if(p.hp>0)drawTank(p,i)});bul.forEach(b=>{x.fillStyle=b.owner?'#ff4d5f':'#ffd84d';x.fillRect(Math.round(b.x-8),Math.round(b.y-8),16,16);x.fillStyle='#fff6a0';x.fillRect(Math.round(b.x-3),Math.round(b.y-3),6,6)});parts.forEach(s=>{if(s.kind==='smoke'){x.globalAlpha=Math.max(0,s.t/.9)*.5;x.fillStyle='#b8c0c4';x.beginPath();x.arc(s.x,s.y,s.r*(1+(1-s.t)*.8),0,Math.PI*2);x.fill();x.globalAlpha=1}else{x.fillStyle='#ffbd32';x.fillRect(Math.round(s.x-2),Math.round(s.y-2),s.r,s.r)}});const active=ps.map((p,i)=>p.bonus?`J${i+1}: ${TYPES[p.bonus].icon} ${TYPES[p.bonus].name} ${Math.ceil(p.bonusT)}s`:'').filter(Boolean).join('   ');document.getElementById('tankInfo').textContent=`❤️ ${ps[0].hp} : ${ps[1].hp}   🏆 ${scores[0]}-${scores[1]}${active?'   '+active:''}`;if(roundPause>0&&!over){x.fillStyle='rgba(0,0,0,.68)';x.fillRect(0,0,W,H);x.textAlign='center';x.fillStyle='#fff';x.font='bold 54px monospace';x.fillText(`¡GANA JUGADOR ${pendingWinner}!`,W/2,H/2);x.font='bold 24px monospace';x.fillText(`Ronda ${scores[0]+scores[1]+1} · siguiente ronda...`,W/2,H/2+55)}if(over){x.fillStyle='rgba(0,0,0,.78)';x.fillRect(0,0,W,H);x.textAlign='center';x.fillStyle='#fff';x.font='bold 56px monospace';x.fillText(`¡GANA JUGADOR ${scores[0]>scores[1]?1:2}!`,W/2,H/2);x.font='bold 24px monospace';x.fillText(`Mejor de 3 · ${scores[0]}-${scores[1]} · Pulsa ↻ para volver a jugar`,W/2,H/2+55)}}
function loop(now){const dt=Math.min(.032,(now-last)/1000);last=now;if(!over){if(roundPause>0){roundPause=Math.max(0,roundPause-dt);if(roundPause===0)resetRound()}else{ps.forEach((p,i)=>{p.cd=Math.max(0,p.cd-dt);if(p.bonusT>0){p.bonusT-=dt;if(p.bonusT<=0){p.bonus=null;p.shield=0;p.bounces=0}}moveTank(p,dt);if(Math.hypot(p.joy.x,p.joy.y)>.08)fire(i)});bul.forEach(b=>updateBullet(b,dt));for(let i=bul.length-1;i>=0;i--)if(bul[i].dead)bul.splice(i,1);bon.forEach(b=>b.life-=dt);for(let i=bon.length-1;i>=0;i--){if(bon[i].life<=0){bon.splice(i,1);continue}for(const p of ps)if(p.hp>0&&Math.hypot(p.x-bon[i].x,p.y-bon[i].y)<TANK_R+b.r){applyBonus(p,bon[i]);explosion(bon[i].x,bon[i].y,true);bon.splice(i,1);break}}spawn-=dt;if(spawn<=0){spawnBonus();spawn=5.5+Math.random()*4.5}parts.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.t-=dt});for(let i=parts.length-1;i>=0;i--)if(parts[i].t<=0)parts.splice(i,1)}}draw();raf=requestAnimationFrame(loop)}requestAnimationFrame(loop);document.getElementById('tankReset').onclick=()=>{cancelAnimationFrame(raf);open()}}
css();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook,{once:true});else hook();
})();
